function [] = ClearPath()
%ClearPath Removes All Toolboxes From The Search Path
pathlist = strsplit(path, ':');
for i=1:1:length(pathlist)
	if (~isempty(strfind(pathlist{i}, 'toolbox')))
		if (~isempty(strfind(pathlist{i}, 'bioinfo')) || ...
				~isempty(strfind(pathlist{i}, 'control')) || ...
				~isempty(strfind(pathlist{i}, 'curvefit')) || ...
				~isempty(strfind(pathlist{i}, 'dsp')) || ...
				~isempty(strfind(pathlist{i}, 'images')) || ...
				~isempty(strfind(pathlist{i}, 'optim')) || ...
				~isempty(strfind(pathlist{i}, 'signal')) || ...
				~isempty(strfind(pathlist{i}, 'physmod')) || ...
				~isempty(strfind(pathlist{i}, 'distcomp')) || ...
				~isempty(strfind(pathlist{i}, 'stm')) || ...
				~isempty(strfind(pathlist{i}, 'stats')) || ...
				~isempty(strfind(pathlist{i}, 'symbolic')) || ...
				~isempty(strfind(pathlist{i}, 'stateflow')) || ...
				~isempty(strfind(pathlist{i}, 'instrument')) || ...
				~isempty(strfind(pathlist{i}, 'slcontrol')))
% 			rmpath(pathlist{i});
		end
	end
end
end