function [success] = sendHandshakeChatResponsePacket(channel, tempKey, user, chatID, key)
%sendHandshakeChatResponsePacket Tell The Client That The Handshake HasCompleted
packet = struct('Type', 'ChatShakeResponse',...
	'User', user,...
	'ChatID', chatID,...
	'Key', tempKey...
	);
success = sendMessage(channel, packet, key);
end