function [success] = sendChatRenamedPacket(channel, name, id, key)
%sendChatRenamedPacket Tell the client the chat was renamed
	packet = struct(	'Type', 'ChatRenamed',...
						'Name', name,...
						'ChatID', id...
						);
	success = sendMessage(channel, packet, key);
end