function [success] = sendChatStartedPacket(channel, name, id, key)
%sendChatStartedPacket Tell the client the chat was started
	packet = struct(	'Type', 'StartedChat',...
						'Name', name,...
						'ID', id...
						);
	success = sendMessage(channel, packet, key);
end