function [success] = sendChatRekeyPacket(channel, id, owner, key)
%sendChatStartedPacket Tell the client the chat was started
	packet = struct(	'Type', 'Rekey',...
						'Owner', owner,...
						'ID', id...
						);
	success = sendMessage(channel, packet, key);
end