function [success] = sendChatRenamedPacket(channel, name, id, key)
%sendChatRenamedPacket Tell The Clients That The Name Of The Chat Room Has Changed
packet = struct('Type', 'ChatRenamed',...
	'Name', name,...
	'ChatID', id...
	);
success = sendMessage(channel, packet, key);
end