function [success] = sendChatRekeyPacket(channel, id, owner, key)
%sendChatRekeyPacket Tell The Clients That They Must Rekey The Chat Room To Keep It Secure
packet = struct('Type', 'Rekey',...
	'Owner', owner,...
	'ID', id...
	);
success = sendMessage(channel, packet, key);
end