function [success] = sendHandshakeChatPacket(channel, tempKey, chatID, key)
%sendHandshakeChatPacket Initiate A Handshake With The Owner Of The Chat Room
packet = struct('Type', 'ChatShake',...
	'ChatID', chatID,...
	'Key', tempKey...
	);
success = sendMessage(channel, packet, key);
end