function [structure] = loginRequest(username, password)
%loginRequest Create a request to log into the server
	password = MD5.hash(password);
	structure = struct(	'Type', 'Login',...
						'Username', username,...
						'Password', password...
						);
end