function [success] = sendChatPacket(chatID, string)
%sendChatPacket Send a message packet to the server
	packet = struct(	'Type', 'Message',...
						'Message', string,...
						'ChatID', chatID...
						);
	success = sendMessage(channel, packet);
end