function [success] = sendHandshakeChatDonePacket(channel, tempKey, user, chatID, chatKey, key)
%sendHandshakeChatDonePacket Let The Initializing Client Know That The Handshake Is Complete
packet = struct('Type', 'ChatShakeDone',...
	'User', user,...
	'ChatID', chatID,...
	'ChatKey', chatKey,...
	'Key', tempKey...
	);
success = sendMessage(channel, packet, key);
end