function [success] = sendChatInvitePacket(channel, chatID, username, key)
%sendChatInvitePacket Invite A Client To A Chat Room
packet = struct('Type', 'ChatInvite',...
	'ID', chatID,...
	'Name', username...
	);
success = sendMessage(channel, packet, key);
end