function [success] = sendChatPacket(channel, sender, chatID, string, key)
%sendChatPacket Send a message packet to the server
	packet = struct(	'Type', 'Message',...
						'Message', string,...
						'Sender', sender,...
						'ChatID', chatID...
						);
	success = sendMessage(channel, packet, key);
end