function [success] = sendHandshakePacket(channel, tempKey, step)
%sendHandshakePacket Create a handshake packet and send it to the channel
	packet = struct(	'Type', 'Shake',...
						'Step', step,...
						'Key', mat2str(tempKey)...
						);
	success = sendMessage(channel, packet, []);
end