function [success] = sendChatPacket(channel, sender, chatID, string, key)
%sendChatPacket Send A Chat Message To The Server Or The Clients
packet = struct('Type', 'Message',...
	'Message', string,...
	'Sender', sender,...
	'ChatID', chatID...
	);
success = sendMessage(channel, packet, key);
end