function [success] = sendHandshakePacket(channel, key, step)
%sendHandshakePacket Create a handshake packet and send it to the channel
	packet = struct(	'Type', 'Shake',...
						'Step', step,...
						'Key', mat2str(key)...
						);
	success = sendMessage(channel, packet);
end