function [success] = sendHandshakePacket(channel, key, step)
%sendHandshakePacket Send A Handshake Packet Between The Client And Server At Pre-Login To Establish A Secure Connection
packet = struct('Type', 'Shake',...
	'Step', step,...
	'Key', key...
	);
success = sendMessage(channel, packet, []);
end