function [success] = sendHandshakeChatResponsePacket(channel, tempKey, user, key)
%sendHandshakeChatPacket Create a handshake packet and send it to the channel
	packet = struct(	'Type', 'ChatShakeResponse',...
						'User', user,...
						'Key', tempKey...
						);
	success = sendMessage(channel, packet, key);
end